spring:
  application:
    name: feign-client
server:
  port: 9981
feign-data:
<<<<<<< Updated upstream
  url: "http://localhost:9983"
=======
  url: "http://localhost:9983"
weather:
  api:
    url: "https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst"
    key: "1234"
>>>>>>> Stashed changes
