server:
  port: 9002
spring:
  application:
    name: order-service
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:mysql://localhost:3307/order}
    username: root
    password: 1234
polar:
  catalog-service-uri: ${CATALOG_SERVICE_URL:http://localhost:9001}