spring:
  application:
    name: api-client
server:
  port: 1234
weather:
  api:
    url: "http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst"
    key: "opV76JHAiKh6IJH3slJZ%2FehqPP8EBGXFGc7B1JXb%2BOMfnx%2BmYKljlDXhMoJNwrxX4bvyUjglvUpUYl7TmgRFWA%3D%3D"